version: '3'

services:
  db:
    container_name: 'pongporn-postgres'
    image: 'postgres:latest'
    ports:
      - 54322:5432
    environment:
      - POSTGRES_USER='bellnew21'
      - POSTGRES_PASSWORD='1p@ssw0rd66'
    restart: 'unless-stopped'
    
  pgadmin:
    container_name: 'pongporn-pgadmin'
    image: 'dpage/pgadmin4:latest'
    ports:
      - 8080:80
    environment:
    - PGADMIN_DEFAULT_EMAIL='pongporn1346@gmail.com'
      - PGADMIN_DEFAULT_PASSWORD='1p@ssw0rd66'
    restart: 'unless-stopped'
  
  strapi:
    container_name: 'pongporn-strapi'
    image: dpage/pgadmin4:latest
    ports:
      - 1337:1337
    environment:
      - name=value
      - DATABASE_CLIENT 'postgres'
      - DATABASE_HOST='172.28.176.1'
      - DATABASE_PORT='54322'
      - DATABASE_NAME='strapi4'
      - DATABASE_USERNAME='bellnew21'
      - DATABASE_PASSWORD='1p@ssw0rd66'
      - DATABASE_SSL='false'
    restart: 'unless-stopped'