version: '3'

services:
  db:
    container_name: 'pongporn-postgres'
    image: 'pongporn:latest'
    ports:
      -54322:54322
    environment:
      -POSTGRES_USER=${DB_USER}
      -POSTGRES_PASSWORD=${DB_PASS}
    image: postgres:14.4
    restart: 'unless-stopped'